### ISSUE TITLE
Use functions in options rather than preset data attributes

### ISSUE THREAD

**Issue by maxkfranz** [monprin/polywas#3]
The layout depends on specific data attributes, like `type: 'snp'`.  It would be better if instead you had functions in `options` so that the dev can specify the data more flexibly.

**Comment by monprin** [comment]
In 0d30d32 I added options for the selectors that define the genes and snps, but what is the canonical way for attaching specific pieces of data for using in placement? At a minimum I need the chromosome (for the snp) , snp and local degree (for the gene), and the start and end base pair (for both). Any recommendations would be greatly appreciated!

**Comment by maxkfranz** [comment]
For those cases you listed, you could have something like:

``` js
isSnp: function( ele ){
  return ele.is('[type = "snp"]');
}
```

The dev can specify a selector like I have, or they can have their own logic in the function.  Using similar functions to get `chrom`, `start`, `end`, etc would also be great.

If you want options like `isSnp` to also directly allow selectors for brevity (i.e. `isSnp: '[type = "snp"]'`), you can use something like:

``` js
var typeofStr = typeof '';

var is = function( ele, condition ){
  if( typeof condition === typeofStr ){
    return ele.is( condition );
  } else {
    return condition( ele );
  }
};

var isEleSnp = is( ele, options.isSnp );
```

**Comment by monprin** [comment]
Done with 3bcbb39

**Comment by maxkfranz** [comment]
Oops, forgot to add Polywas to the extension list before.  Added now: https://github.com/cytoscape/cytoscape.js/commit/e6f406c32b3402939cec742ed93e344702a3c36e
